version: 2

run:
  skip-dirs:
    - examples
  tests: false  # 测试文件需要适配新接口，暂时跳过
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "declared and not used"  # 某些示例代码可能有未使用的变量
  exclude-rules:
    # 暂时跳过测试文件的检查（需要适配新接口）
    - path: _test\.go
      linters:
        - typecheck
        - unused
    # 保留 server/routes.go 中的预留 API handlers
    - path: server/routes\.go
      text: "is unused"
      linters:
        - unused
    # 保留 server/middleware.go 中待实现的中间件
    - path: server/middleware\.go
      text: "is unused"
      linters:
        - unused
