# golangci-lint configuration (v2.x)
version: "2"

run:
  timeout: 5m
  tests: true
  go: '1.21'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
        - (io.Closer).Close
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
